name: fluttermoji
description: A light-weight and highly customizable SVG graphic set for Flutter, which provides a Customizer Widget, CircleAvatar and other utility functions.
version: 0.1.1
# author: Suraj Kumar
homepage: https://github.com/psk907/fluttermoji

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.12+4
  flutter_svg: ^0.19.1
  get: ^3.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - attributeicons/
